/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Chess;

import Pieces.Board;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Board gameBoard = new Board();


    }
}
