/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Chess;

import GameSession.GameStart;
import Pieces.Board;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        GameStart gameSession = new GameStart();

        gameSession.printGameBoard(gameSession.getGameBoard());
    }
}
